import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthModal from "@/components/AuthModal";
import Providers from "@/components/Providers";
import ThemeToggle from "@/components/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-4 flex items-center justify-between border-b sticky top-0 bg-white/70 dark:bg-zinc-950/70 backdrop-blur z-40">
          <div className="flex items-center gap-3">
            <div className="font-semibold tracking-tight">AXIO QR</div>
          </div>
          <div className="flex items-center gap-2">
            <ThemeToggle />
            <AuthModal />
          </div>
        </div>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
